<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>uuid</key>
    <string>77AC23B6-8A90-11D9-BAA4-000A9584EC8D</string>
    <key>name</key>
    <string>Tidea</string>
    <key>scopeName</key>
    <string>text.Tidea</string>
    <key>fileTypes</key>
    <array>
    <string>txt</string>
    </array>
    <key>patterns</key>
    <array>
        <dict>
            <key>name</key>
            <string>unicode.symbol</string>
            <key>match</key>
            <string>°|¹|²|³|⁴|⁵|⁶|⁷|⁸|⁹|⁽|⁾|♔|♕|♖|♗|♘|♙|♚|♛|♜|♝|♞|♟|♠|♡|♢|♣|♤|♥|♦|♧|☎|☏|☐|☑|☒|☓|✁|✂|✃|✄|✅|✆|✇|✈|✉|✎|✏|✐|✑|✒|✓|✔|✕|✖|✗|✘|♩|♪|♫|♬|♭|♮|♯|☠|☡|☢|☣|☤|☥|☦|☧|☨|☩|☪|☫|☬|☭|☮|☯|♀|♂|♨|☀|☁|☂|☃|☄|★|☆|☇|☈|☉|☊|☋|☌|☍|☔|☚|☛|☜|☝|☞|☟|☹|☺|☻|✙|✚|✛|✜|✝|✞|✟|♁|♃|♄|♅|♆|♇|♈|♉|♊|♋|♌|♍|♎|♏|♐|♑|♒|♓</string>
        </dict>
        <dict>
            <key>name</key>
            <string>tidea.link.external</string>
            <key>match</key>
            <string>(ftp:\/\/|https?:\/\/)?([\w\.-]+)\.[a-z]{2,6}(\.|\/)\S*</string>
        </dict>

        <dict>
            <key>name</key>
            <string>variable.parameter.link.email</string>
            <key>match</key>
            <string>[^\s][\w\.-]+@[\w-]+\.[a-z\.]{2,6}</string>
        </dict>

        <dict>
            <key>name</key>
            <string>tidea.link.internal</string>
            <key>match</key>
            <string>\[\[[^\]]+\]\]| .+?? </string>
        </dict>

        <dict>
            <key>name</key>
            <string>Alternatives</string>
            <key>begin</key>
            <string>\[</string>
            <key>end</key>
            <string>\]</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>comment.line, tidea.gray</string>
                </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>comment.line, tidea.gray</string>
                </dict>
            </dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>name</key>
                    <string>comment.line, tidea.gray</string>
                    <key>match</key>
                    <string>/</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>$self</string>
                    <key>name</key>
                    <string>ThisAlternative</string>
                    <key>match</key>
                    <string>.+?</string>
                </dict>
            </array>
        </dict>

        <dict>
            <key>comment</key>
            <string>First dash in new line exclude spaces</string>
            <key>name</key>
            <string>tidea.firstchar</string>
            <key>match</key>
            <string>^(?:\s*)- |(?&lt;!\.)\.$</string>
        </dict>

        <dict>
            <key>comment</key>
            <string>Hightlight U+202d</string>
            <key>name</key>
            <string>invalid, tidea.hightlight</string>
            <key>match</key>
            <string>‭.+?‭</string>
        </dict>

        <dict>
            <key>comment</key>
            <string>Gray color U+202c</string>
            <key>name</key>
            <string>comment.line, tidea.gray</string>
            <key>match</key>
            <string>‬.+?‬</string>
        </dict>

        <dict>
            <key>comment</key>
            <string>Red color U+200b</string>
            <key>name</key>
            <string>keyword.control, tidea.red</string>
            <key>match</key>
            <string>​.+?​</string>
        </dict>

        <dict>
            <key>comment</key>
            <string>Orange color U+202a</string>
            <key>name</key>
            <string>variable.parameter, tidea.orange</string>
            <key>match</key>
            <string>‪.+?‪</string>
        </dict>

        <dict>
            <key>comment</key>
            <string>Phone number</string>
            <key>name</key>
            <string>constant.numeric.txt</string>
            <key>match</key>
            <string>(?&lt;=[^\w\.])(0[93418]|[1-9]\d)[\.\d]{6,10}(?!(\.\d|\w))</string>
        </dict>

        <dict>
            <key>comment</key>
            <string>bold U+200e</string>
            <key>match</key>
            <string>‎.+?‎</string>
            <key>name</key>
            <string>tidea.bold</string>
        </dict>

        <dict>
            <key>comment</key>
            <string>italic U+200f</string>
            <key>match</key>
            <string>‏.+?‏</string>
            <key>name</key>
            <string>tidea.italic</string>
        </dict>

         <dict>
            <key>comment</key>
            <string>Symbol for terminology</string>
            <key>match</key>
            <string>(^|\s)(:)(\S[\w\d _-{}]*\S)(:)(\s|$)</string>
            <key>captures</key>
            <dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>meta.class.tidea.symbol</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>tidea.gray</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>tidea.gray</string>
                </dict>
            </dict>
        </dict>
    </array>
</dict>
</plist>
